apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: student089
  name: dep-gamingwebapp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gamingwebapp
    spec:
      containers:
      - name: gamingwebapp
        terminationMessagePath: "/tmp/gamingwebapp-log"
        image: xpiritbv/gamingwebapp
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: LeaderboardApiOptions__BaseUrl
          value: http://svc-leaderboardwebapi
        - name: ApplicationInsights__InstrumentationKey
          value: 59cf101a-97fa-481d-b1aa-f13e6dc14767
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: "0.10"
      nodeSelector:
        beta.kubernetes.io/os: linux